name: Publish Handler

on:
  issues:
    types: [opened, reopened]
concurrency:
  group: catalog-${{ github.ref }}
  cancel-in-progress: false
permissions:
  contents: write
  issues: write
jobs:
  handle_publish:
    if: contains(github.event.issue.labels.*.name, 'publish')

    runs-on: ubuntu-latest
    env:
      URL: ${{ github.event.issue.title }}
    steps:
      - uses: actions/checkout@v5
        with:
          repository: nounfve-deploy/save_point_publish
          ref: publish
      - uses: nounfve-deploy/save_point_publish/.github/use_sp@master
      - run: |
          set -u 
          export REPO=$(echo $URL|grep -oP 'https://github.com/\K.*?(?=/releases/tag/.*)')
          export TAG=$(echo $URL|grep -oP '.*?/releases/tag/\K.+')
          gh release download $TAG --repo $REPO
          for zip in *.zip;            
          do save_point catalog add $zip --url "https://github.com/${REPO}/releases/download/${TAG}/${zip}" --use publish/catalog.yaml;
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update catalog"
          file_pattern: "publish/**"
      - run: >
          gh issue close ${{ github.event.issue.number }} 
          --comment "Processing completed"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
